version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - config:/config:z
      - ./videos:/media/videos:ro
      - ./release/2.0.1.0:/config/plugins/JellyJav
    ports:
      - 127.0.0.1:8896:8096

volumes:
  config:
